// flow-typed signature: 96310aba54fa3cd3378e4da0fc850dc1
// flow-typed version: <<STUB>>/minireset.css_v^0.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minireset.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minireset.css' {
  declare module.exports: any;
}
